language: go

os:
  - linux
  - osx

go:
  - tip
  - 1.11
  - "1.10"

install:
  - go get github.com/issue9/assert

script: go test -race -v -coverprofile=coverage.txt -covermode=atomic $(go list ./...)
